name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this if your branch name is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug SSH Connection
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -vvv -o StrictHostKeyChecking=no -i private_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} exit

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i private_key.pem -r . ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/AWSProjects

      - name: Deploy Application
        run: |
          ssh -i private_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd /home/ec2-user/AWSProjects
          git pull origin main
          chmod +x deploy.sh
          ./deploy.sh
          EOF

